name: Deploy to Firebase Hosting

# Push on either stage or main
on: 
  push:
    branches:
      - main
      - stage

    paths:
      - 'client/**'


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: client
        run: npm install
      
      - name: Env setup
        working-directory: client
        run: |
          if [ "${{ github.ref_name }}" == "stage" ]; then
            echo -e "${{ secrets.STAGE_FRONTEND_ENV }}" > .env
          else
            echo -e "${{ secrets.PRODUCTION_FRONTEND_ENV }}" > .env
          fi

      - name: Build App
        working-directory: client
        run: |
          CI=false npm run build
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPEKBOOM_MAPPER }}
          target: ${{ github.ref_name == 'stage' && 'staging' || 'production' }}